FROM mongo:6.0.2-focal

# TODO: get from env vars
ENV MONGO_INITDB_ROOT_DATABASE=exampleDB
ENV MONGO_INITDB_ROOT_USERNAME=user
ENV MONGO_INITDB_ROOT_PASSWORD=pass

COPY ./scripts/db/init-mongo.js /docker-entrypoint-initdb.d/
