version: '3'
services:
  # Data base container:
  mongodb:
    build:
      context: .
      dockerfile: ./Dockerfile.mongoDB
    restart: always
    environment:
      - MONGO_INITDB_ROOT_DATABASE=${DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
      - DB_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}

  # Server container
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_URL=${DB_URL}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    healthcheck:
      test: curl --connect-timeout 90 --max-time 90 --retry 4 --retry-delay 30 --retry-max-time 90 --retry-connrefused "http://localhost:3000/healthcheck" | sh
      interval: 5s
      timeout: 30s
      retries: 6